### ISSUE TITLE
.askWhen is not a function

### ISSUE THREAD

**Issue by tunnckoCore** [generate/generate-dest#1]
raw output

```
~/foobar  
% ❯ gen dest project                                                                                       July 09, 02:24:26
[02:24:45] starting generate
[02:24:45] changing cwd to ~/foobar
[02:24:45] ✔ running tasks: [ 'dest', 'project' ]
[02:24:45] starting generate.dest 
TypeError: app.question(...).askWhen is not a function
    at Task.fn (/home/charlike/.nvm/versions/node/v6.3.0/lib/node_modules/generate-dest/generator.js:39:8)
    at /home/charlike/.nvm/versions/node/v6.3.0/lib/node_modules/generate/node_modules/composer/lib/task.js:115:22
    at Task.runDeps (/home/charlike/.nvm/versions/node/v6.3.0/lib/node_modules/generate/node_modules/composer/lib/task.js:79:12)
    at Task.run (/home/charlike/.nvm/versions/node/v6.3.0/lib/node_modules/generate/node_modules/composer/lib/task.js:107:8)
    at /home/charlike/.nvm/versions/node/v6.3.0/lib/node_modules/generate/node_modules/composer/lib/flow.js:25:22
    at Task.runDeps (/home/charlike/.nvm/versions/node/v6.3.0/lib/node_modules/generate/node_modules/composer/lib/task.js:83:10)
    at Task.run (/home/charlike/.nvm/versions/node/v6.3.0/lib/node_modules/generate/node_modules/composer/lib/task.js:107:8)
    at /home/charlike/.nvm/versions/node/v6.3.0/lib/node_modules/generate/node_modules/composer/lib/flow.js:25:22
    at Generate.Composer.build (/home/charlike/.nvm/versions/node/v6.3.0/lib/node_modules/generate/node_modules/composer/index.js:155:10)
    at build (/home/charlike/.nvm/versions/node/v6.3.0/lib/node_modules/generate/node_modules/base-generators/lib/generate.js:51:15)
```

images

![2016-07-09-02 24 59_1280x1024_scrot](https://cloud.githubusercontent.com/assets/5038030/16704218/39ae8312-457d-11e6-86ca-84fb70203563.png)
![2016-07-09-02 25 41_1280x1024_scrot](https://cloud.githubusercontent.com/assets/5038030/16704217/39a2671c-457d-11e6-9437-70d7c97b0374.png)
![2016-07-09-02 32 04_1280x1024_scrot](https://cloud.githubusercontent.com/assets/5038030/16704233/626daa08-457d-11e6-896f-fbd7f811937b.png)

It seems the problem is simple, that's just report. Problem comes from that that `app.questions`'s returned instance don't have `.askWhen` method because something here in [ask-when/index.js#L52-L61](https://github.com/jonschlinkert/ask-when/blob/master/index.js#L52-L61).

Quick fix will be to just `app.questions.askWhen` or `app.askWhen` [instead of chaining on L38-L39](https://github.com/generate/generate-dest/blob/master/generator.js#L38-L39).

**Comment by jonschlinkert** [comment]
> Quick fix will be to just app.questions.askWhen or app.askWhen

good idea, I'll look at it now

**Comment by jonschlinkert** [comment]
thanks a lot for creating these issues. this is how these libs get better, fast!

**Comment by tunnckoCore** [comment]
Yeyy. :D I'll try with fixes, `generate-project` seems to work now.

Now i'm waiting better "customizable templates / overriding templates", because don't like that `~/generate/ ...`, you know my state about that things. Best place is through the stores which are already in hidden world, or through local package.json, but not just one more unhidden place somewhere. :)

**Comment by jonschlinkert** [comment]
> Best place is through the stores which are already in hidden world

yep, for now (a few days, maybe a week or two) it's going to be hard coded to `~/templates` until I get it wired up to use paths defined in the config store. then you will be able to customize just about anything. 

I'll link an issue to this...

**Comment by tunnckoCore** [comment]
I know, i just love you. :heart_eyes:  :laughing:

**Comment by jonschlinkert** [comment]
lol thx

**Comment by jonschlinkert** [comment]
btw, have you used `update`? I couldn't live without that lib. we've used it for almost two years, I'm glad we finally got it released

edit: I have 25-30 "updaters" to publish. I'm getting them published slowly but surely

**Comment by jonschlinkert** [comment]
and [this](https://github.com/generate/generate-project/blob/master/index.js#L157-L167). How could it possibly be much simpler to create a generator? lol

**Comment by tunnckoCore** [comment]
> btw, have you used update?

not yet.

> and this. How could it possibly be much simpler to create a generator? lol

Yea, absolutely... I don't know, but all around is freakin. I can't believe it, srsly. :D And the logos... want some like them for @postjson and @limonjs haha

**Comment by jonschlinkert** [comment]
> And the logos

here is your man: https://www.fiverr.com/obus88. He does great work

**Comment by jonschlinkert** [comment]
I think it's time for us to talk about generate and update! not quite ready with verb yet, but close :)
